### ISSUE TITLE
ejs completion isn't working 

### ISSUE THREAD

**Issue by tribhuwan-kumar** [yaegassy/coc-html-css-support#6]
I'm trying to get `ejs` completion, But its not working as I expected.
this is my `coc-settings.json`
```json
{
    "html-css-support.enabledLanguages": [
        "ejs",
        "html",
        "vue",
        "blade",
        "htmldjango",
        "typescriptreact",
        "javascriptreact",
    ],
}
```
How can I do it ? I've searched across the web but didn't find any solution!

**Comment by yaegassy** [comment]
Due to changes in coc.nvim's functionality, it seems that the `html-css-support.enabledLanguages` settings could not be used in the workspace-specific `.vim/coc-settings.json`, although there were no issues with the global `coc-settings.json`.

I have adjusted this and published a new version of `coc-html-css-support` to npm, so please give it a try.
